// Copies public/arnie.md into a TS module so the API route can import it without fs at runtime.
import fs from "fs";
const md = fs.readFileSync("public/arnie.md", "utf8");
fs.writeFileSync("lib/arnie.generated.ts", `// Generated by scripts/gen-arnie.mjs from public/arnie.md. Do not edit.\nexport const ARNIE_MD = ${JSON.stringify(md)};\n`);
console.log("lib/arnie.generated.ts written,", md.length, "chars");
